# Generated by Django 4.2.16 on 2024-12-11 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('gchoice', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('fname', models.TextField(default='Golfer1', max_length=10)),
                ('lname', models.TextField(default='Golfer1Lname', max_length=10)),
                ('g_phone', models.CharField(default='555-867-5309', max_length=15)),
                ('g_email', models.CharField(default='bob.smith@aol.com', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Misc_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_date', models.DateField(default=django.utils.timezone.now)),
                ('purch_id', models.IntegerField(default=1)),
                ('inv_id', models.IntegerField(default=1)),
                ('inv_description', models.CharField(default='Hat', max_length=255)),
                ('ichoice', models.TextField(choices=[('TE', 'Tees'), ('PH', 'Premium Hat'), ('RH', 'Regular Hat'), ('DOZ', 'Dozen Golf Balls'), ('SL', 'Sleeve Golf Balls'), ('IND', 'Individual Golf Ball'), ('CR', 'Club Rental'), ('OTH', 'Other')], default=('RH', 'Regular Hat'), max_length=50)),
                ('misc_quantity', models.IntegerField(default=1)),
                ('misc_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('misc_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('misc_tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('misc_total', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Golf_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_date', models.DateField(default=django.utils.timezone.now)),
                ('gp_id', models.IntegerField(default=1, unique=True)),
                ('num_18_players', models.IntegerField(default=1)),
                ('holes_18_price', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('num_9_players', models.IntegerField(default=1)),
                ('holes_9_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('num_18_carts', models.IntegerField(default=1)),
                ('num_9_carts', models.IntegerField(default=1)),
                ('cart_9_price', models.DecimalField(decimal_places=2, default=9.0, max_digits=10)),
                ('cart_18_price', models.DecimalField(decimal_places=2, default=12.0, max_digits=10)),
                ('golf_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('golf_tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('golf_total', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Golf_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_date', models.DateField(default='2024-11-24')),
                ('tee_time', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 23, 59, 59))),
                ('no_in_party', models.PositiveIntegerField(default=4)),
                ('avg_grp_hcp', models.PositiveIntegerField(default=26)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer')),
            ],
        ),
    ]
