# Generated by Django 4.2.16 on 2024-11-28 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_golfer', models.BooleanField(default=False)),
                ('fname', models.TextField(default='Golfer1')),
                ('lname', models.TextField(default='Golfer1Lname')),
                ('g_phone', models.CharField(default='55-867-5309', max_length=15)),
                ('g_email', models.CharField(default='bob.smith@aol.com', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='inv_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_name', models.CharField(default='Tees', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField(default=1)),
                ('inv_description', models.CharField(default='Hat', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inv_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.inv_options')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=2)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='golfproapp.OrderItem', to='golfproapp.inventory'),
        ),
        migrations.CreateModel(
            name='Golfing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_time', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 23, 59, 59))),
                ('no_in_party', models.PositiveIntegerField(default=4)),
                ('avg_grp_hcp', models.PositiveIntegerField(default=26)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer')),
            ],
        ),
    ]
