# Generated by Django 4.2.16 on 2024-12-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golf_purchases',
            old_name='customer_id',
            new_name='customer_purchases',
        ),
    ]
