# Generated by Django 4.2.16 on 2024-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_data',
            name='holes',
            field=models.IntegerField(default=18),
        ),
    ]
