# Generated by Django 4.2.16 on 2024-11-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golf_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holes_18_price', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('holes_9_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('cart_9_price', models.DecimalField(decimal_places=2, default=9.0, max_digits=10)),
                ('cart_18_price', models.DecimalField(decimal_places=2, default=12.0, max_digits=10)),
                ('golf_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('golf_tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('golf_total', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Misc_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField(default=1)),
                ('inv_description', models.CharField(default='Hat', max_length=255)),
                ('misc_quantity', models.IntegerField(default=1)),
                ('misc_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('misc_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('misc_tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('misc_total', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Golfing',
            new_name='Golf_Data',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inv_options',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='inv_options',
        ),
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
