# Generated by Django 4.2.16 on 2024-12-08 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_purchases',
            name='gp_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 12, 8, 1, 15, 34, 899006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='misc_purchases',
            name='mp_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 12, 8, 1, 15, 34, 898563, tzinfo=datetime.timezone.utc)),
        ),
    ]
