# Generated by Django 4.2.16 on 2024-12-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_purchases',
            name='num_18_carts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='golf_purchases',
            name='num_18_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='golf_purchases',
            name='num_9_carts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='golf_purchases',
            name='num_9_players',
            field=models.IntegerField(default=1),
        ),
    ]
