# Generated by Django 4.2.16 on 2024-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0002_golf_purchases_num_18_carts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc_purchases',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='misc_purchases',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
