# Generated by Django 4.2.16 on 2024-12-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0002_golf_purchases_misc_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc_purchases',
            name='customer_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer'),
        ),
        migrations.AlterField(
            model_name='golf_data',
            name='customer_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer'),
        ),
        migrations.AlterField(
            model_name='golf_purchases',
            name='customer_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='golfproapp.customer'),
        ),
    ]
