# Generated by Django 4.2.16 on 2024-12-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0002_rename_customer_id_golf_purchases_customer_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golf_purchases',
            name='customer_purchases',
        ),
    ]
