# Generated by Django 4.2.16 on 2024-12-09 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0003_remove_misc_purchases_customer_id_misc_purchases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc_purchases',
            name='mp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
