# Generated by Django 4.2.16 on 2024-12-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0004_golf_purchases_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_purchases',
            name='golf_purchase_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='misc_purchases',
            name='misc_purchase_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
