# Generated by Django 4.2.16 on 2024-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0005_alter_golf_purchases_golf_purchase_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golf_purchases',
            old_name='golf_purchase_id',
            new_name='gp_id',
        ),
        migrations.RemoveField(
            model_name='misc_purchases',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misc_purchases',
            name='misc_purchase_id',
        ),
        migrations.AddField(
            model_name='misc_purchases',
            name='customer_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misc_purchases',
            name='purch_id',
            field=models.IntegerField(default=1),
        ),
    ]
