# Generated by Django 4.2.16 on 2024-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0006_rename_golf_purchase_id_golf_purchases_gp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.TextField(default='Golfer1', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.TextField(default='Golfer1Lname', max_length=10),
        ),
        migrations.AlterField(
            model_name='golf_data',
            name='avg_grp_hcp',
            field=models.PositiveIntegerField(default=26, max_length=2),
        ),
        migrations.AlterField(
            model_name='golf_data',
            name='no_in_party',
            field=models.PositiveIntegerField(default=4, max_length=1),
        ),
    ]
