# Generated by Django 4.2.16 on 2024-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0008_alter_golf_data_avg_grp_hcp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gchoice',
            field=models.CharField(choices=[('Yes', 'No')], default='Yes', max_length=3),
            preserve_default=False,
        ),
    ]
