# Generated by Django 4.2.16 on 2024-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0010_remove_customer_is_golfer_alter_customer_gchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc_purchases',
            name='ichoice',
            field=models.TextField(choices=[('TE', 'Tees'), ('PH', 'Premium Hat'), ('RH', 'Regular Hat'), ('DOZ', 'Dozen Golf Balls'), ('SL', 'Sleeve Golf Balls'), ('IND', 'Individual Golf Ball'), ('CR', 'Club Rental'), ('OTH', 'Other')], default=('RH', 'Regular Hat'), max_length=50),
        ),
    ]
