# Generated by Django 4.2.16 on 2024-12-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0011_misc_purchases_ichoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_purchases',
            name='gp_date',
            field=models.DateField(default='2024-12-05'),
        ),
    ]
