# Generated by Django 4.2.16 on 2024-12-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfproapp', '0012_golf_purchases_gp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_data',
            name='golf_date',
            field=models.DateField(default='2024-11-24'),
        ),
    ]
